language: ruby

rvm:
  - 2.3.1

bundler_args: --without development

before_script:
  - cp config/database.yml.travis config/database.yml

script:
  - RAILS_ENV=test bundle exec rake db:setup --trace
  - bundle exec rspec spec
