db:
  image: postgres:9.3
  volumes:
    - ~/.docker-volumes/organize2/db:/var/lib/postgresql/data
  expose:
    - '5432'

web:
  build: .
  volumes:
    - .:/app
  ports:
    - '8081:3000'
  links:
    - db
