development: &postgres
  adapter: postgresql
  encoding: unicode
  username: postgres
  database: organize2_development
  pool: 5

test:
  <<: *postgres
  database: organize2_test

production:
  <<: *postgres
  database: organize2_production
