# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 88624447445afb56bfb7cfbb55af0f7e977afe191b5dc46b3f293edaf3549f0507ca281ec656096aa0a481e4d86cad33a2af2431f5bab3a41ec25227d6f0318a

test:
  secret_key_base: 64d61688934065dec3ffe99dfaed4b4cb315671694f025c5b432bd5b8433edcf0e3b776c46287815c215b50e18976988479dbe08ee9a2884fad98eaeb4303721

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
